### ISSUE TITLE
Opts not able to be passed in to http client

### ISSUE THREAD

**Issue by AlexanderMann** [amperity/vault-clj#10]
# Motivation
In debugging some production issues I came to find it necessary to be able to pass in call options for `clj-http`. Things like `insecure?`, `socket-timeout`, etc. I ended up pulling the logic in the http client out and calling private vars. It'd be great if I could either specify some default opts on the client itself (so as to not have to effect the top-level defprotocol) or pass them in somehow. This would probably eliminate all of the instances that I find myself having to pull the guts out of `vault.http`.

**Comment by greglook** [comment]
This seems like a good improvement. :+1:

**Comment by AlexanderMann** [comment]
A workaround I came up with since writing this which _might_ be more appropriate is using the `with-middleware` functionality present in `clj-http`. That ends up providing a _little_ more flexibility, but it's definitely not as plug and play as an opt pass in.
