### ISSUE TITLE
Update to support Vault 0.10.0

### ISSUE THREAD

**Issue by greglook** [amperity/vault-clj#13]
This version makes some deprecations and changes to how leases are renewed and revoked.
https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#080-august-9th-2017

**Comment by ieugen** [comment]
Latest vault version is 1.7.x+ . 
Is this still an issue?

**Comment by greglook** [comment]
Nope, just an old ticket. We've run against 1.3.2 for a while.
