### ISSUE TITLE
Mount Point Path

### ISSUE THREAD

**Issue by pgrech2** [amperity/vault-clj#27]
Currently no support for mount_point path. Is this something of interest? I have a use case and happy to contribute but will likely be a significant change. Here is an example of mount_point path implementation by Python library hvac. 

https://hvac.readthedocs.io/en/stable/_modules/hvac/api/auth_methods/ldap.html?highlight=mount_point

**Comment by greglook** [comment]
Interesting - I think this *is* something we want to support, though I will point out that `vault-clj` isn't really meant to be used for configuration or server management. Taking a quick look at the auth code, it seems like we could implement this by passing the `:mount-point` through the credentials maps in the `authenticate!` call without having to change very much.

**Comment by pgrech2** [comment]
Passing `:mount-point` through `authenticate!` looks like it should work well. The next decision would be to support a `default-mount-point` for each of the various `authenticate` functions. Thoughts?

**Comment by pgrech2** [comment]
I created a branch and completed this. Is there anyway I can push my branch for a PR?

**Comment by drassaby** [comment]
This issue was resolved with #34 . Thanks @pgrech2!
