### ISSUE TITLE
301 Moved Permanently should be supported with a warning

### ISSUE THREAD

**Issue by sflanker** [amperity/vault-clj#31]
If somebody accidentally includes a leading `/` in their secret path vault returns a 301 Moved Permanently with a corrected URL that doesn't include the extra slash.

Current behavior: vault-clj/write-secret! returns false with no helpful information whatsoever. Have fun debugging

Expected behavior: follow the redirect, write the secret, warn the user that they should update their config so that they don't keep getting 301s.

**Comment by greglook** [comment]
The 2.x version does path-trimming and also supports redirects, so this should no longer be an issue.
