### ISSUE TITLE
Add Support for the KV V2 Secrets Engine

### ISSUE THREAD

**Issue by drassaby** [amperity/vault-clj#33]
### Design considerations:
- Vault has many secret engines, and will likely have more in the future. This means the client should be as extensible as possible to support each of these operations
- Using these operations should be as simple as possible
- The entire enhancement can be done without breaking backwards compatibility

### Proposed implementation:

1. From common functions shared by all secret engines (eg. CRUD operations on secrets), call multi-methods that dispatch based on the secret engine type. If the secret engine is not inputted, default to the generic secret engine operations (current behavior).
2. Add additional functions to the http client and mock client to support the KV V2 API
3. Expose additional functions in a kv-mount protocol. This protocol will either be in the `vault.core` namespace or in its own namespace. Here’s a breakdown of the arguments for both options:
    - `vault.core` already contains all the other exposed functions. It’s an easy go to file to read up on what functions an end user should call. This may be harder to use as the client adds support for more secret engines over time since functions are not separated into their own namespaces. For example, `read-metadata` is an operation that cannot be called on a `generic` secret engine. This concern could be largely ameliorated by a clear naming strategy (eg. prefixing all kv v2 specific functions with kv)
    - A custom namespace would allow users to know exactly what functions correspond with kv mounts. Usage would be along the lines of `(kv-mount/read-metadata <PATH>)`. This has a few benefits. First, autocomplete in any editor will give you a much shorter list of possible operations to look through (no matter how many secret engines are supported). Second,  it becomes much harder for an end user to accidentally use the wrong method because it’s much more explicit. Finally, it won’t balloon the size of `vault.core` as new engines are added. However, this is in many ways less discoverable than adding the protocol to `vault.core`. There would no longer be a centralized place to see all possible client operations, so users may not know an operation is available.

**Comment by drassaby** [comment]
Happy to hear any feedback about the implementation proposal from anybody!

@greglook @pyncc  any thoughts?

**Comment by greglook** [comment]
I'd need to brush up on the differences between the old generic API and the new KV APIs to give a more definitive answer, but my initial thought is that we should maintain the generality of the methods in the core vault namespace. It'd be odd to me as a consumer to see 90% of the methods in one namespace and a handful in another, as you point out.

If we wanted to go the separate-ns route, I'd propose an entirely new major version and maybe moving _everything_ to dedicated namespaces. That might be overkill if we can fit the KV engine into the existing secrets patterns, though.

**Comment by drassaby** [comment]
@greglook 
I agree that if we go the separate namespace route and don't mind breaking backwards compatibility the cleanest way would be to move everything to dedicated namespaces. Personally, I think it might make sense to do this conversion given the [number of Vault secret engines](https://www.vaultproject.io/docs/secrets/kv/kv-v2.html) we may want to support in the future. It looks like the [Vault ruby client]( https://github.com/hashicorp/vault-ruby) has a similar concept (except built around objects instead of namespaces).

#### [Generic secret store in the ruby client:](https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/api/logical.rb)
- Reading from a generic secret store (like our current implementation):
```ruby
Vault.logical.read("secret/bacon")
```
- Our equivalent would look like:
```clojure
(vault-logical/read <PATH>)
```

#### [KV secret store in the ruby client:](https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/api/kv.rb)
- Reading from a kv secret store:
```ruby
Vault.kv.read("secret/bacon")
```
- Other methods not possible on generic secret stores are also available:
```ruby
Vault.kv.read_metadata("secret/bacon")
```
- Our equivalent would look like:
```clojure
(vault-kv/read <PATH>)
```

</br>
</br>
</br>

With everything being moved to distinct namespaces (even the generic/logical lookup) like you suggested, this becomes even more precise.
I would think that users are less likely to call:
```clojure
(vault-logical/read <PATH AT KV MOUNT>)
```
when they mean:
```clojure
(vault-logical/read <PATH AT KV MOUNT>)
```

</br>

Then they would with the alternate approach where they might call:
```clojure
(vault/read <PATH AT KV MOUNT>)
```
instead of:
```clojure
(vault/kv-read <PATH AT KV MOUNT>)
```

**Comment by pyncc** [comment]
I think the core namespace should be expanded slightly unless there is a well-developed design for supporting other secret backends. If just the key-value v2 backend is considered, there aren't many additional methods to add, at least not enough to move into their own ns.

The existing read method can be used by callers to read v2 nodes by adding the extra /data/ path segment already. I don't think consumers of this library are at high risk of using the wrong read method (kv-read vs read).

This is especially unlikely when considering the different signature likely needed to support referring to secret mount point and path separately.

> This may be harder to use as the client adds support for more secret engines over time 

The argument to split out the core ns is less compelling until the time when more secret backends are actually supported. That just feels like premature optimisation when there are no current plans to do so.

In the example you give from the Ruby library, "secret" is the mount point, and "bacon" is the path. It's not clear to me how this method would distinguish mount from path in order to inject "data" in the correct location. Thus, the signature of thus key-value v2 likely would have to be something other than just a string, which means the caller wouldn't likely substitute the two by mistake.

**Comment by drassaby** [comment]
@pyncc  @greglook thanks for the comments! Let's move discussion to #35 for now,  and come back here and summarize if that's scrapped
