### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by greglook** [amperity/vault-clj#5]
Test coverage is pretty abysmal right now - roughly 22% according to cloverage. We should write tests to exercise the behavior of the client in as many cases as possible and improve coverage to _at least_ 75%.

This should be supported by using a CI system to automatically run tests. Current preference is CircleCI and Codecov.

**Comment by aengelberg** [comment]
+1 for adding tests, especially for the mock client :)

**Comment by ieugen** [comment]
One option would be to run tests using testcontainers and start an actual vault instance with an in-memory. 
We can test against multiple vault instance.

**Comment by greglook** [comment]
This is basically done in the 2.x branch.
