### ISSUE TITLE
`read-secret` request options are not honored when renewing/rotating secrets

### ISSUE THREAD

**Issue by brandonvin** [amperity/vault-clj#52]
`read-secret` allows you to pass extra request options as the `:request-opts` key. For example, with an AWS secrets engine, you could pass `:request-opts {:query-params {:ttl ,,,}}` to in order to generate a set of temporary credentials with a customized TTL. If you want to automatically renew/rotate these credentials, you would also pass `:renew true :rotate true` options. However, the request options containing the custom value of `:ttl` won't be used again after the secret expires and is re-read. Here's a relevant portion of code, where the renewal code currently passes an empty map of options irrespective of the original options passed to `read-secret`. https://github.com/amperity/vault-clj/blob/20d16f6a4992c95d000f3c964dbbdaf961f9168b/src/vault/lease.clj#L193

**Comment by greglook** [comment]
Fixed in 2.x
