### ISSUE TITLE
Support babashka 

### ISSUE THREAD

**Issue by ieugen** [amperity/vault-clj#53]
Hi, 

We are using babashka tasks to deploy. 
We store secrets in vault and would like to get secrets using babashka tasks as well. 

Would you consider supporting babashka (implementing or accepting PR's ) ? 

From the look at the library, the dependencies are quite common and should work. 
`clojure.tools.logging` does not seem to work. 
Babashka does not have built-in logging but this could be used: https://gist.github.com/borkdude/c97da85da67c7bcc5671765aef5a89ad

Babashka can interpret clojure code using sci and supports quite a few clojure libraries https://github.com/babashka/babashka/blob/master/doc/projects.md .

This could be achieved if the bits that are not supported are re-implemented with bits that are supported by babashka.

Bellow is a ample babashka script to help with development.
bb.edn
```
;; Type bb tasks to see all tasks
;; Type bb <task-name> or bb run <task-name> to run a task
{:min-bb-version "0.4.0"
 :paths ["script"]
 :deps {amperity/vault-clj {:mvn/version "1.0.3"}}
 :tasks {:requires ([vault.core :as vault]
                    [vault.client.http])
         :init     (do 
                       (def client (vault/new-client "https://vault.do.drevidence.com:8200")))
         ;; Helpers
         vault-get-dev {:doc "Get dev secrets from vault - requires vault cli."
                            :task (do 
                                    (client))}
}}

```

```
bb vault-get-dev
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Could not resolve symbol: clojure.lang.LockingTransaction/isRunning
Location: clojure/tools/logging.clj:59:15
Phase:    analysis

----- Context ------------------------------------------------------------------
55:   [logger level throwable message]
56:   (if (case *force*
57:         :agent  true
58:         :direct false
59:         (and (clojure.lang.LockingTransaction/isRunning)
                  ^--- Could not resolve symbol: clojure.lang.LockingTransaction/isRunning
60:              (*tx-agent-levels* level)))
61:     (send-off *logging-agent*
62:       (fn [_#] (impl/write! logger level throwable message)))
63:     (impl/write! logger level throwable message))
64:   nil)
```

**Comment by greglook** [comment]
Looks like the issue is with `tools.logging`'s use of agents, which as I understand it are not 1:1 supported in babashka.

**Comment by borkdude** [comment]
@greglook Agents are supported in babashka, it just doesn't give access to `clojure.lang.LockingTransAction` which is a pretty low level thing,

**Comment by noakohavi** [comment]
Hi, is there a solution for that issue?

**Comment by borkdude** [comment]
@noakohavi An alternative is shelling out to the vault CLI.

**Comment by noakohavi** [comment]
I ran into this problem when trying to require this: aerospike-clj.client, not vault, and got the same error.

**Comment by ieugen** [comment]
> @noakohavi An alternative is shelling out to the vault CLI.

I think the idea of having vault-clj HTTP client is to avoid the need to install vault-cli binary (191MB ?!) .
Vault exposes an HTTP API - that the vault cli and vault-clj use.

**Comment by borkdude** [comment]
Another idea: if the original libraries won't support babashka you can go ahead and fork them to make it work, possible contribute back to the original repo or maintain a trimmed down / alternative fork.

**Comment by borkdude** [comment]
Btw, another option is to make pods out of these libraries:

https://github.com/babashka/pods

**Comment by borkdude** [comment]
I am currently looking into adding logging to babashka in the form of clojure.tools.logging + an implementation (probably timbre).

https://github.com/babashka/babashka/discussions/926#discussioncomment-989191

This may be one step closer to compatibility with this library.

**Comment by ieugen** [comment]
I've built babashka from main branch and the error changed:

```
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Unable to resolve classname: java.io.BufferedInputStream
Location: clj_http/util.clj:5:3

----- Context ------------------------------------------------------------------
1: (ns clj-http.util
2:   "Helper functions for the HTTP client."
3:   (:require [clojure.string :refer [blank? lower-case split trim]]
4:             [clojure.walk :refer [postwalk]])
5:   (:import [java.io BufferedInputStream ByteArrayInputStream ByteArrayOutputStream EOFException InputStream PushbackInputStream]
     ^--- Unable to resolve classname: java.io.BufferedInputStream
6:            [java.net URLDecoder URLEncoder]
7:            [java.util.zip DeflaterInputStream GZIPInputStream GZIPOutputStream InflaterInputStream]
8:            org.apache.commons.codec.binary.Base64
9:            org.apache.commons.io.IOUtils))
10: 

----- Stack trace --------------------------------------------------------------
clj-http.util                             - clj_http/util.clj:5:3
clj-http.conn-mgr                         - clj_http/conn_mgr.clj:3:3
clj-http.client                           - clj_http/client.clj:4:3
vault.client.api-util                     - vault/client/api_util.clj:2:3
vault.authenticate                        - vault/authenticate.clj:3:3
vault.client.http                         - vault/client/http.clj:3:3
user-2cdc70cb-1dad-407d-9100-360d5474b81a - <expr>:5:47
```

**Comment by ieugen** [comment]
I think the dependency on clj-http is a show stopper. 
I checked the dependencies on that and there are quite a few java libraries there.

At this point I don't think it's feasible to make vault-clj work with babashka because of the jar dependencies.

If I am not alone in this perhaps we can close the issue and look for alternative implementations that don't depend on java jars.

```
  :dependencies [[org.apache.httpcomponents/httpcore "4.4.14"]
                 [org.apache.httpcomponents/httpclient "4.5.13"]
                 [org.apache.httpcomponents/httpclient-cache "4.5.13"]
                 [org.apache.httpcomponents/httpasyncclient "4.1.4"]
                 [org.apache.httpcomponents/httpmime "4.5.13"]
                 [commons-codec "1.15"]
                 [commons-io "2.8.0"]
                 [slingshot "0.12.2"]
                 [potemkin "0.4.5"]]
```

**Comment by borkdude** [comment]
@ieugen You can fork this library and replace the usage of clj-http with babashka.curl or org.httpkit.client which are available in bb.

**Comment by ieugen** [comment]
@noakohavi : I have a draft PR for making this work with babashka. 
Can someone please check it out?

The changes can be split into smaller sets but my question is: are you ok with changes overall? 
I'm also cc'ing @pyncc  since he is a reviewer.

**Comment by borkdude** [comment]
If the maintainers of this lib aren't open to switchting to httpkit as the client, then perhaps an idea to make the http client flexible is to introduce a protocol, like `clojure.tools.logging` does:

```
(defprotocol HttpClient
  (get [this url])
  (post [this url])
  (put [this url])
  (delete [this url])
```

so you can bring your own http client and set it using `(alter-var-root #'library/*http-client* client)`.

In bb you would then do:

```
(require '[org.httpkit.client :as client])
;; no deftype available in bb yet, so we use record
(defrecord Client [] HttpClient (get [this url] @(client/get url)) ...)
(alter-var-root #'library/*http-client* (->Client))
```  
and for clj-http users they can do something similar.

**Comment by borkdude** [comment]
An alternative would be to use reader conditionals for `:bb` and `:clj` for the JVM impl.

**Comment by borkdude** [comment]
Btw @ieugen, nice job!
