### ISSUE TITLE
The endpoints sys/renew, sys/revoke, sys/revoke-prefix, sys/revoke-force have been deprecated and relocated under sys/leases

### ISSUE THREAD

**Issue by ezraroi** [amperity/vault-clj#59]
Need to stop using endpoints that were deprecated 4 years ago (2017)

**Comment by ieugen** [comment]
@greglook : Any ETA on the 2.x rewrite ?

**Comment by greglook** [comment]
I'm going to be pretty busy the next month and a half, so at a guess, sometime in October.

**Comment by greglook** [comment]
I guess I didn't say which October... 😅
