### ISSUE TITLE
Specs for authenticate (and other APIs)?

### ISSUE THREAD

**Issue by bsless** [amperity/vault-clj#66]
Hello,
What do you think about adding clojure.spec.alpha specs to `authenticate` and possibly other parts of the public API, similar to how cognitect's AWS client validates requests before sending them?

I wouldn't mind PRing it

Thanks,
Ben

**Comment by greglook** [comment]
I'm generally in favor of more validation, as long as it doesn't get in the way of compatibility with different versions of the vault API.

**Comment by bsless** [comment]
My idea in particular was to spec `authenticate!` itself https://github.com/amperity/vault-clj/blob/master/src/vault/core.clj#L12

**Comment by greglook** [comment]
I'm open to further validation of the requests on APIs, however I don't think we can use clojure.spec and retain babashka compatibility. For example, in ac8a864b0277751b436367aa90160257ed64efce I switched to a really simplified validation approach for the auth and lease states.
