### ISSUE TITLE
Support OIDC authentication

### ISSUE THREAD

**Issue by ieugen** [amperity/vault-clj#67]
We switched from using github auth to using OIDC auth via Azure AD + groups.
Company is using Office 365 and we can leverage MS Auth and Security groups for Vault access. 

Interested in supporting this functionality.

**Comment by greglook** [comment]
Sure, happy to add that to the base library as long as it doesn't require pulling in any Azure-specific dependencies. If it does, then this can be provided in a separate library like [amperity/vault-clj-aws](https://github.com/amperity/vault-clj-aws)

**Comment by ieugen** [comment]
IMO it should not require any AWS specific parts.
When the vault client does oidc auth it opens a browser to authenticate to Azure AD. 
Not sure how this will be handled.
I hope to get a chance to look at this in the upcoming weeks.

**Comment by ieugen** [comment]
Not sure if this will be feasible outside of a gui environment since oidc relised on the user authenticating over a browser.
