### ISSUE TITLE
[2.x] Update documentation for new major version

### ISSUE THREAD

**Issue by greglook** [amperity/vault-clj#86]
Update the README and any other documentation necessary for the switch to the new 2.x version. In particular, this should include an updated "how to use this" and "migration from 1.x" guides.

**Comment by jasonjckn** [comment]
can I know your plans for v2? 
Are you still planning to release this?

**Comment by greglook** [comment]
Yeah, there hasn't been much activity on the branch because we wound up vendoring the code in our monorepo for final production testing. The plan is to backport any changes to this open-source version and then drop the vendored code once the migration is finished. That's looking like it'll be in the next couple of weeks, at which point we'd be ready to finalize 2.x and make it the new main version.
